mode: auto

avatar:
  url: /image/tou.jpg # 你的头像图片地址
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: 😭
    message: 不想上班
  
favicon: /favicon.ico
albums:
  enable: true

pages:
  - name: 小可爱们
    url: /girls/
    icon: fluent:animal-cat-28-filled
    color: dodgerblue
  - name: 留影册
    url: /albums/
    icon: material-symbols:all-inbox-sharp
    color: dodgerblue
  
github_issues:
  enable: false

github_discussions:
  enable: false

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      title: 文档
      path: /archives/
      icon: ri:archive-line
    - type: categories
      title: 记录
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      title: 标签
      path: /tags/
      icon: ri:price-tag-3-line
      
  custom:
    title: 设置
    path: https://yun.yunyoujun.cn/guide/
    icon: ri:settings-line

categories:
- Diary

tags:
  动画: orange
  漫画: orange
  游戏: orange
  小说: orange
  Parcel: '#21374b'
  学习: saddlebrown
  MAD: crimson
  教程: royalblue
  笔记: dimgray
  分享: '#0078e7'
  随笔: mediumpurple
  Blender: '#d04d2d'
  Linux: '#2577b1'
  科幻: midnightblue
  蚂蚁森林: '#54a892'

social:
  - name: GitHub
    link: https://github.com/AkiSeele
    icon: ri:github-line
    color: '#181717'
  - name: 哔哩哔哩动画
    link: https://space.bilibili.com/12087145
    icon: ri:bilibili-line
    color: '#FF8EB3'
  - name: E-Mail
    link: mailto:a2371445972@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: 微博
    link: https://weibo.com/u/6162682416
    icon: ri:weibo-line
    color: '#E6162D'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=333109340
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 知乎
    link: https://www.zhihu.com/people/zong-shi-ri-bo-xi-shan
    icon: ri:zhihu-line
    color: '#0084FF'
  
  # - name: Twitter
  #   icon: ri:twitter-line
  #   color: '#1da1f2'

# 标语动画
# enable: 是否开启
# title: 设置文字内容
# border: 是否开启标语中字符的左右边框
# cloud: 在首页下方显示流动的云
# enable: 是否开启
# color: 自定义色彩
# go_down: 向下箭头按钮（点击翻页）

banner:
  enable: true
  title: 舰舰的奇妙见闻
  color: #9BD5FC
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: false
  content: 好耶！是大冒险!


bg_image:
  enable: true
  url: https://s1.ax1x.com/2022/10/08/xGJ5zd.jpg
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8


footer:
  live_time:
    enable: true
    prefix: 本博客努力运行了
    suffix: ᕦ(･ㅂ･)ᕤ
    start_time: '2022-10-01T00:00:00'
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'
    url: 
    title: 可爱滴捏
  powered:
    enable: false
  beian:
    enable: true
    icp: 鄂ICP备2022016601号-1
    # 公安备案
    gongan:
      enable: false
      text: 京公网安备 XXXXXXXX 号
      id: XXXXXXXX
  support:
    enable: true
    title: 又拍云
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://s1.ax1x.com/2022/10/18/xrUBHx.png
    prefix: 本网站由
    suffix: 提供 CDN 加速

fireworks:
  enable: true
  colors:
    - '155, 212, 252'
    - '234, 80, 144'
    - '92, 160, 225'

girls:
  enable: true

wordcloud:
  enable: true

# 评论
comment:
  enable: true

waline:
  enable: true
  serverURL: https://example.akibro.top
  # visitor: true
  comment: false


giscus:
  enable: false
  repo:
  repo-id:
  category:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light


# 开启一键复制按钮
codeblock:
  copy_btn: true

# 设置文章的分享版权
creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false

# 打赏
reward:
  enable: false
  comment: 我很穷，请给我钱（伸手）
  methods:
    - name: 支付宝
      path: /image/zfbQian.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
      # link: https://xxxx
    - name: QQ 支付
      path: /image/qqQian.jpg
      color: '#12B7F5'
      icon: ri:qq-line
    - name: 微信支付
      path: /image/wxQian.jpg
      color: '#2DC100'
      icon: ri:wechat-pay-line

post_edit:
  enable: true
  url: https://github.com/AkiSeele/AkiSeele.github.io/tree/hexo/source/


# 文章#
# 内容卡片
post_card:
  opacity: 0.6

say:
  enable: true
  api: /data/sentences.json
  # https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

