/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/2023_1_Recom': RouteRecordInfo<'/posts/2023_1_Recom', '/posts/2023_1_Recom', Record<never, never>, Record<never, never>>,
    '/posts/BLEACH': RouteRecordInfo<'/posts/BLEACH', '/posts/BLEACH', Record<never, never>, Record<never, never>>,
    '/posts/Echarts': RouteRecordInfo<'/posts/Echarts', '/posts/Echarts', Record<never, never>, Record<never, never>>,
    '/posts/eightysix': RouteRecordInfo<'/posts/eightysix', '/posts/eightysix', Record<never, never>, Record<never, never>>,
    '/posts/ExerciseNotes': RouteRecordInfo<'/posts/ExerciseNotes', '/posts/ExerciseNotes', Record<never, never>, Record<never, never>>,
    '/posts/live2d': RouteRecordInfo<'/posts/live2d', '/posts/live2d', Record<never, never>, Record<never, never>>,
    '/posts/NamingRules': RouteRecordInfo<'/posts/NamingRules', '/posts/NamingRules', Record<never, never>, Record<never, never>>,
    '/posts/Re_0': RouteRecordInfo<'/posts/Re_0', '/posts/Re_0', Record<never, never>, Record<never, never>>,
    '/posts/SakuraPoetry': RouteRecordInfo<'/posts/SakuraPoetry', '/posts/SakuraPoetry', Record<never, never>, Record<never, never>>,
    '/posts/SAO': RouteRecordInfo<'/posts/SAO', '/posts/SAO', Record<never, never>, Record<never, never>>,
    '/posts/StarrySkyTrain': RouteRecordInfo<'/posts/StarrySkyTrain', '/posts/StarrySkyTrain', Record<never, never>, Record<never, never>>,
    '/posts/vite': RouteRecordInfo<'/posts/vite', '/posts/vite', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
